title: My Tech Blog
# uncomment baseurl if you want to publish the site to a subfolder
baseurl: /blog
description: Something interesting
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
include:
- google887a8a7a755952ec.html
highlighter: rouge
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    baseurl: "/blog"
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: rouge
