title: My Tech Blog
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: Something interesting
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
